ARG PHP_VERSION=7.1

FROM php:${PHP_VERSION}-apache

ENV APACHE_DOCUMENT_ROOT /var/www/eccube/

RUN printf '%s\n' \
    'deb [check-valid-until=no] http://snapshot.debian.org/archive/debian/20191118T000000Z buster main' \
    'deb [check-valid-until=no] http://snapshot.debian.org/archive/debian-security/20191118T000000Z buster/updates main' \
    'deb [check-valid-until=no] http://snapshot.debian.org/archive/debian/20191118T000000Z buster-updates main' \
    > /etc/apt/sources.list \
    && apt-get update && apt-get install -y --no-install-recommends \
    apt-transport-https \
    apt-utils \
    build-essential \
    curl \
    debconf-utils \
    gcc \
    git \
    vim \
    gnupg2 \
    libfreetype6-dev \
    libicu-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    libpq-dev \
    libzip-dev \
    locales \
    ssl-cert \
    unzip \
    zlib1g-dev \
    libwebp-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && echo "en_US.UTF-8 UTF-8" >/etc/locale.gen \
    && locale-gen \
    ;

RUN docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
    && docker-php-ext-configure gd --with-freetype-dir --with-jpeg-dir --with-webp-dir \
    && docker-php-ext-install -j$(nproc) zip gd mysqli pdo_mysql opcache intl pgsql pdo_pgsql \
    ;

RUN pecl install apcu && echo "extension=apcu.so" > /usr/local/etc/php/conf.d/apc.ini

RUN apt-get update \
    && apt-get install -y --no-install-recommends nodejs npm \
    && apt-get clean \
    ;

RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf \
    && sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf \
    ;

RUN a2enmod rewrite headers ssl
    RUN ln -s /etc/apache2/sites-available/default-ssl.conf /etc/apache2/sites-enabled/default-ssl.conf
    EXPOSE 443

WORKDIR ${APACHE_DOCUMENT_ROOT}
